import { FormEvent, useState } from 'react'
import { BarChart3, Clock3, Medal, Search, Swords, Trophy, UserRound } from 'lucide-react'
import { PlayerProfileResponse } from '../types/player'
import { useI18n } from '../i18n'
const API = 'http://127.0.0.1:4000/api/v1/player/'
const duration = (s: number) => `${Math.floor(s / 60)}:${String(s % 60).padStart(2, '0')}`
export function PlayerProfilePanel() {
 const { t, locale } = useI18n(); const [identity, setIdentity] = useState(''); const [data, setData] = useState<PlayerProfileResponse | null>(null); const [loading, setLoading] = useState(false); const [error, setError] = useState('')
 const load = async (event: FormEvent) => { event.preventDefault(); if (!identity.trim()) return; setLoading(true); setError(''); try { const r = await fetch(`${API}${encodeURIComponent(identity.trim())}`); const body = await r.json(); if (!r.ok) throw new Error(body.detail || 'Unable to load profile'); setData(body) } catch (e) { setError(e instanceof Error ? e.message : 'Unable to load profile') } finally { setLoading(false) } }
 return <section className="profile-shell"><div className="profile-heading"><div><span className="eyebrow">PUBLIC MATCH HISTORY</span><h2>{t('profileTitle')}</h2><p>{t('profileDescription')}</p></div><BarChart3 size={25}/></div><form className="profile-search" onSubmit={load}><Search size={17}/><input value={identity} onChange={e => setIdentity(e.target.value)} placeholder={t('profilePlaceholder')} /><button disabled={loading}>{loading ? t('loading') : t('analyzeProfile')}</button></form>{error && <p className="profile-error">{error}</p>}{!data && !error && <div className="profile-empty"><UserRound size={27}/><div><strong>{t('profileReady')}</strong><p>{t('profilePrivacy')}</p></div></div>}{data && <><div className="player-card"><img src={data.player.avatar || ''} alt=""/><div><h3>{data.player.name}</h3><span>Steam ID · {data.player.account_id}</span></div><div className="rank-label"><Medal size={16}/>{data.player.rank_tier ? `${t('rank')}: ${data.player.rank_tier}` : t('rankUnavailable')}</div></div><div className="profile-stats"><article><Trophy size={17}/><b>{data.player.win_rate}%</b><span>{t('winRate')}</span></article><article><Swords size={17}/><b>{data.player.matches}</b><span>{t('totalMatches')}</span></article><article className="wins"><b>{data.player.wins}W · {data.player.losses}L</b><span>{t('record')}</span></article></div><div className="history-heading"><h3>{t('recentMatches')}</h3><span>{t('scoreNote')}</span></div><div className="match-history">{data.matches.map(m => <article className={`history-row ${m.result}`} key={m.match_id}><div className="result-chip">{m.result === 'win' ? t('win') : t('loss')}</div><div><strong>{m.hero_name}</strong><span><Clock3 size={12}/>{new Date(m.started_at * 1000).toLocaleDateString(locale === 'ru' ? 'ru-RU' : 'en-US')} · {duration(m.duration)}</span></div><div className="kda"><b>{m.kills}/{m.deaths}/{m.assists}</b><span>K / D / A</span></div><div className="match-metric"><b>{m.gpm}</b><span>GPM</span></div><div className="match-metric"><b>{m.xpm}</b><span>XPM</span></div><div className="performance"><b>{m.performance_score}</b><span>/100</span></div><p>{locale === 'ru' ? (m.takeaway.includes('Farm') ? 'Главная точка роста — темп фарма.' : m.takeaway.includes('deaths') ? 'Береги жизнь: смерти забрали слишком много времени.' : 'Проверь следующий объект после каждой драки.') : m.takeaway}</p></article>)}</div></>}</section>
}
